{{- if not .Values.artemis.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-service.artemisSecretName" . }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.artemis.credentials.username | quote }}
  password: {{ .Values.artemis.credentials.password | quote }}
{{- end }}
