services:
  artemis:
    image: apache/activemq-artemis:2.44.0
    container_name: artemis
    restart: unless-stopped # todo: what is it??
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    # volumes:
      # configuration - mount to laptop's disk
#      - ./broker/config/broker.xml:/var/lib/artemis-instance/etc/broker.xml
#      - ./broker/config/artemis-users.properties:/var/lib/artemis-instance/etc/artemis-users.properties
#      - ./broker/config/artemis-roles.properties:/var/lib/artemis-instance/etc/artemis-roles.properties
      # data - mount to docker's volume
      #- artemis-data:/var/lib/artemis-instance/data
    ports:
      - "61616:61616" # JMS
      - "8161:8161"   # Web Console
    networks:
      - artemis-network
#    healthcheck:
#      test:
#        [
#          "CMD",
#          "curl",
#          "-f",
#          "http://localhost:8161"
#        ]
#      interval: 10s
#      timeout: 5s
#      retries: 10

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
#      SPRING_PROFILES_ACTIVE: docker
      ARTEMIS_URL: tcp://artemis:61616
    ports:
      - "8081:8081"
    depends_on:
      - artemis
        # condition: service_healthy
    networks:
      - artemis-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "8082:8082"
    depends_on:
      - artemis
      # condition: service_healthy
    networks:
      - artemis-network

networks:
  artemis-network:

volumes:
  artemis-data:
