spring:
  application:
    name: order-service

  config:
    import: optional:classpath:order-contract.yml

  artemis:
    # mode = embedded - when artemis is launched inside the application - just for learning purposes
    mode: native
    broker-url: ${ARTEMIS_URL}
    # user and password - that are created by docker-compose file
    user: ${ARTEMIS_USER}
    password: ${ARTEMIS_PASSWORD}

#  jms:
#    listener:
#      acknowledge-mode: auto
#      concurrency: 2-10
#
#    template:
#      delivery-mode: non_persistent
#      priority: 4
#      receive-timeout: 5000
#      qos-enabled: true

server:
  port: 8081
