apiVersion: v2
name: inventory-service
description: Deploys inventory-service

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# This is the chart version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "1.0"
