# instead of
# ./broker/config/broker.xml
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "artemis.fullname" . }}-config

data:
  broker.xml: |-
{{ .Files.Get "files/broker.xml" | indent 4 }}
  artemis-users.properties: |-
{{ .Files.Get "files/artemis-users.properties" | indent 4 }}
  artemis-roles.properties: |-
{{ .Files.Get "files/artemis-roles.properties" | indent 4 }}