apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "artemis.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "artemis.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "artemis.fullname" . }}

    spec:
      initContainers:
        - name: init-artemis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          command:
            - sh
            - -c
            - |
              set -e
              if [ ! -f /var/lib/artemis-instance/bin/artemis ]; then
                echo "Creating Artemis instance"
                /opt/activemq-artemis/bin/artemis create /var/lib/artemis-instance --user ${ARTEMIS_USER} --password ${ARTEMIS_PASSWORD} --silent
              else
                echo "Artemis instance already exists"
              fi

              echo "Copying custom configuration"
              cp /config/* /var/lib/artemis-instance/etc/

          env:
            - name: ARTEMIS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "artemis.fullname" . }}-secret
                  key: ARTEMIS_USER
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "artemis.fullname" . }}-secret
                  key: ARTEMIS_PASSWORD

          volumeMounts:
            - name: data
              mountPath: /var/lib/artemis-instance
            - name: config
              mountPath: /config

      containers:
        - name: artemis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jms
              containerPort: {{ .Values.service.jmsPort }}
            - name: console
              containerPort: {{ .Values.service.consolePort }}

          # env is not used in deployment but might be used by image itself
          env:
            - name: ARTEMIS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "artemis.fullname" . }}-secret
                  key: ARTEMIS_USER
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "artemis.fullname" . }}-secret
                  key: ARTEMIS_PASSWORD

          volumeMounts:
            - name: data
              mountPath: /var/lib/artemis-instance

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "artemis.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "artemis.fullname" . }}-config