# instead of
# environment:
#   ARTEMIS_USER: admin
#   ARTEMIS_PASSWORD: admin
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "artemis.fullname" . }}-secret

type: Opaque

stringData:
  ARTEMIS_USER: {{ .Values.auth.username }}
  ARTEMIS_PASSWORD: {{ .Values.auth.password }}