apiVersion: v1
kind: Secret

metadata:
  name: artemis-secret
  namespace: {{ .Values.namespace}}

type: Opaque

stringData:
  username: {{ .Values.artemis.username }}
  password: {{ .Values.artemis.password }}