image:
  registry: docker.io
  repository: bitnami/postgresql
#  tag: "18.4.0"

auth:
  postgresPassword: postgres
  username: postgres
  password: postgres
  database: orders_db

replicaCount: 1

service:
  type: ClusterIP
  ports:
    postgresql: 5432

primary:
  persistence:
    enabled: true
    size: 1Gi

#broker:
#  configPath: /var/lib/artemis-instance/etc

resources:
  requests:
    cpu: 250m
    memory: 256Mi

  limits:
    cpu: "1"
    memory: 1Gi